name: icapps_fast_barcode_scanner
description: A fast barcode scanner using MLKit on Android and AVFoundation on iOS.
version: 1.2.0
homepage: https://github.com/jhoogstraat/icapps_fast_barcode_scanner
repository: https://github.com/jhoogstraat/icapps_fast_barcode_scanner

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  icapps_fast_barcode_scanner_platform_interface: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

dependency_overrides:
  icapps_fast_barcode_scanner_platform_interface:
    path: ../fast_barcode_scanner_platform_interface

flutter:
  plugin:
    platforms:
      android:
        package: com.icapps.icapps_fast_barcode_scanner
        pluginClass: FastBarcodeScannerPlugin
      ios:
        pluginClass: FastBarcodeScannerPlugin
